version: '3.8'

services:
  
  # --- BROKERS ---

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    ports:
      - '9092:9092'
      - '19092:19092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      CLUSTER_ID: 'ci-Kafka-test-01'
    networks:
      - industrial_net

  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_PLUGINS_ENABLE=rabbitmq_delayed_message_exchange
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - industrial_net

  # --- FRONTEND (Servido con Nginx) ---

  dashboard:
    image: 'nginx:alpine'
    volumes:
      - ./dashboard:/usr/share/nginx/html
    ports:
      - '80:80'
    networks:
      - industrial_net

  # --- FLUJO DE DATOS (KAFKA) ---

  sensor_producer:
    build: ./sensor_producer
    networks:
      - industrial_net
    depends_on:
      - kafka

  alert_detector:
    build: ./alert_detector
    networks:
      - industrial_net
    depends_on:
      - kafka

  plant_monitor_backend:
    build: ./plant_monitor_backend
    ports:
      - '8081:8081'
    networks:
      - industrial_net
    depends_on:
      - kafka

  # --- FLUJO DE DECISIONES (RABBITMQ) ---

  alert_router:
    build: ./alert_router
    networks:
      - industrial_net
    depends_on:
      - kafka
      - rabbitmq

  operator_console_backend:
    build: ./operator_console_backend
    ports:
      - '8082:8082'
    networks:
      - industrial_net
    depends_on:
      - rabbitmq

  action_dispatcher:
    build: ./action_dispatcher
    ports:
      - '8080:8080'
    networks:
      - industrial_net
    depends_on:
      - rabbitmq

  actuator_worker:
    build: ./actuator_worker
    networks:
      - industrial_net
    depends_on:
      - rabbitmq

  maintenance_worker:
    build: ./maintenance_worker
    networks:
      - industrial_net
    depends_on:
      - rabbitmq

networks:
  industrial_net:
    driver: bridge